item_names = {"categories":["weapon", "head", "cape", "neck", "body", "legs", "shield", "hands", "feet", "ring", "ammo"],
"weapon": [
	"Saradomin's blessed sword",
	"3rd age longsword",
	"Abyssal bludgeon",
	"Abyssal dagger",
	"Abyssal tentacle",
	"Abyssal whip",
	"Ancient mace",
	"Arclight",
	"Armadyl godsword",
	"Bandos godsword",
	"Barrelchest anchor",
	"Black salamander",
	"Blade of saeldor",
    "Blade of saeldor (c)",
	"Blisterwood flail",
	"Bone dagger",
	"Brine sabre",
	"Crystal halberd",
	"Crystal halberd (basic)",
	"Crystal halberd (attuned)",
	"Crystal halberd (perfected)",
	"Crystal sceptre",
	"Darklight",
	"Dharok's greataxe",
	"Dinh's bulwark",
	"Dragon 2h sword",
	"Dragon battleaxe",
	"Dragon claws",
	"Dragon dagger",
	"Dragon halberd",
	"Dragon hasta",
	"Dragon hunter lance",
	"Dragon longsword",
	"Dragon mace",
	"Dragon scimitar",
	"Dragon spear",
	"Dragon sword",
	"Dragon warhammer",
	"Elder maul",
	"Event rpg",
	"Fixed device",
	"Gadderhammer",
	"Ghrazi rapier",
	"Inquisitor's mace",
	"Granite hammer",
	"Granite longsword",
	"Granite maul",
	"Guthan's warspear",
	"Ham joint",
	"Hill giant club",
	"Ivandis flail",
	"Keris",
	"Leaf-bladed spear",
	"Leaf-bladed sword",
	"Leaf-bladed battleaxe",
	"Maple blackjack",
	"Maple blackjack(o)",
	"Maple blackjack(d)",
	"Toktz-xil-ek",
	"Tzhaar-ket-em",
	"Tzhaar-ket-om",
	"Crystal pickaxe",
	"Adamant pickaxe",
	"Mithril pickaxe",
	"Black pickaxe",
	"Dragon pickaxe",
	"Steel pickaxe",
	"Iron pickaxe",
	"Bronze pickaxe",
	"Rune pickaxe",
	"Toktz-xil-ak",
	"Rune 2h sword",
	"Rune battleaxe",
	"Rune claws",
	"Rune dagger",
	"Rune halberd",
	"Rune hasta",
	"Rune longsword",
	"Rune mace",
	"Rune scimitar",
	"Rune spear",
	"Rune sword",
	"Rune warhammer",
	"Sarachnis cudgel",
	"Saradomin's blessed sword",
	"Saradomin godsword",
	"Saradomin sword",
	"Scythe of vitur",
	"Slayer's staff",
	"Staff of light",
	"Statius's warhammer",
	"Swift blade",
	"Slayer's staff (e)",
	"Red topaz machete",
	"Staff of the dead",
	"Torag's hammers",
	"Wolfbane",
	"Verac's flail",
	"Vesta's longsword",
	"Viggora's chainmace",
	"Zamorakian spear",
	"Zamorakian hasta",
	"Zamorak godsword",
	"Adamant scimitar",
	"Mithril scimitar",
	"Black scimitar",
	"White scimitar",
	"Steel scimitar",
	"Iron scimitar",
	"Bronze scimitar",
	"3rd age bow",
	"Armadyl crossbow",
	"Black chinchompa",
	"Crystal bow",
	"Crystal bow (basic)",
	"Crystal bow (attuned)",
	"Crystal bow (perfected)",
	"Craw's bow",
	"Dark bow",
	"Dorgeshuun crossbow",
	"Dragon crossbow",
	"Dragon hunter crossbow",
	"Dragon thrownaxe",
	"Rune crossbow",
	"Hunters' crossbow",
	"Adamant crossbow",
	"Mithril crossbow",
	"Steel crossbow",
	"Iron crossbow",
	"Bronze crossbow",
	"Rune thrownaxe",
	"Heavy ballista",
	"Karil's crossbow",
	"Light ballista",
	"Magic comp bow",
	"Magic longbow",
	"Magic shortbow",
	"Magic shortbow (i)",
	"Yew shortbow",
	"Maple shortbow",
	"Willow shortbow",
	"Oak shortbow",
	"Red Chinchompa",
	"Seercull",
	"Toxic blowpipe",
	"Twisted bow",
	"Ahrim's staff",
	"Ancient staff",
	"Black salamander",
	"Crystal staff (basic)",
	"Crystal staff (attuned)",
	"Crystal staff (perfected)",
	"Dawnbringer",
	"Saradomin staff",
	"Iban's staff (u)",
	"Kodai wand",
	"Master wand",
	"Eldritch nightmare staff",
	"Harmonised nightmare staff",
	"Volatile nightmare staff",
	"Nightmare staff",
	"Thammaron's sceptre",
	"Sanguinesti staff",
	"Trident of the seas",
	"Trident of the swamp",
	"Toxic staff of the dead",
	"3rd age wand",
	"Void knight mace",
	"Mystic smoke staff",
	"Smoke battlestaff",
	"Mystic lava staff",
	"Mystic mud staff",
	"Mystic dust staff",
	"Mystic mist staff",
	"Mystic steam staff",
	"Air battlestaff",
	"Water battlestaff",
	"Earth battlestaff",
	"Fire battlestaff"
],
"head": [
	"Neitiznot faceguard",
	"Inquisitor's great helm",
	"Dharok's helm",
	"Dwarven helmet",
	"Fighter hat",
	"Guthan's helm",
	"Helm of neitiznot",
	"Justiciar faceguard",
	"Dragon full helm",
	"Dragon med helm",
	"Rune full helm",
	"Serpentine helm",
	"Slayer helmet (i)",
	"Obsidian helmet",
	"Torag's helm",
	"Verac's helm",
	"Void melee helm",
    "Void ranger helm",
    "Void mage helm",
	"3rd age full helmet",
	"Proselyte sallet",
	"Warrior helm",
	"Berserker helm",
	"Armadyl helmet",
	"Robin hood hat",
	"Karil's coif",
	"Saradomin coif",
	"3rd age range coif",
	"Crystal helm",
	"Archer helm",
	"Snakeskin bandana",
	"Spined helm",
	"Coif",
	"Leather cowl",
	"Ranger hat",
	"3rd age mage hat",
	"Ancestral hat",
	"Ahrim's hood",
	"Elder chaos hood",
	"Infinity hat",
	"Healer hat",
	"Farseer helm",
	"Skeletal helm",
	"Guthix halo",
	"Saradomin halo",
	"Zamorak halo",
	"Saradomin mitre"
],    
"cape": [
	"Infernal cape",
	"Fire cape",
	"Mythical cape",
	"Ardougne cloak 4",
	"Ardougne cloak 3",
	"Ardougne cloak 2",
	"Ardougne cloak 1",
	"Saradomin cloak",
	"Max cape",
	"Strength cape(t)",
	"Obsidian cape",
	"3rd age cloak",
	"Ava's attractor",
	"Ava's accumulator",
	"Ava's assembler",
	"Saradomin cape",
	"Imbued saradomin cape",
	"Guthix cape",
	"Saradomin cape",
	"Zamorak cape",
	"Red cape"
],
"neck": [
	"Amulet of fury",
	"Amulet of torture",
	"Necklace of anguish",
	"Amulet of avarice",
	"Amulet of strength",
	"Amulet of glory",
	"Amulet of power",
	"Salve amulet(i)",
	"Salve amulet(ei)",
	"Berserker necklace",
	"Amulet of the damned",
	"Occult necklace",
	"Amulet of accuracy",
	"Dragonbone necklace",
	"Bonecrusher necklace",
	"3rd age amulet"
],
"body": [
	"Inquisitor's hauberk",
	"Bandos chestplate",
	"Fighter torso",
	"Void knight top",
	"Elite void top",
	"Verac's brassard",
	"Dharok's platebody",
	"Guthan's platebody",
	"Torag's platebody",
	"Obsidian platebody",
	"Proselyte hauberk",
	"Justiciar chestguard",
	"Dragon chainbody",
	"3rd age platebody",
	"Rune platebody",
	"Dragon platebody",
	"Armadyl chestplate",
	"Crystal body",
	"Karil's leathertop",
	"Saradomin d'hide body",
	"Black d'hide body",
	"Red d'hide body",
	"Blue d'hide body",
	"Green d'hide body",
	"Studded body",
	"Snakeskin body",
	"Rangers' tunic",
	"3rd age range top",
	"Spined body",
	"Frog-leather body",
	"Hardleather body",
	"Leather body",
	"Ancestral robe top",
	"Ahrim's robetop",
	"3rd age robe top",
	"Elder chaos top",
	"Infinity top",
	"Mystic robe top",
	"Saradomin robe top",
	"Skeletal top",
	"Monk's robe top"
],
"legs": [
	"Inquisitor's plateskirt",
	"Bandos tassets",
	"Void knight robe",
	"Elite void robe",
	"Verac's plateskirt",
	"Dharok's platelegs",
	"Guthan's chainskirt",
	"Torag's platelegs",
	"Obsidian platelegs",
	"Proselyte cuisse",
	"Justiciar legguards",
	"3rd age platelegs",
	"Dragon platelegs",
	"Rune platelegs",
	"Armadyl chainskirt",
	"Crystal legs",
	"Karil's leatherskirt",
	"Saradomin chaps",
	"3rd age range legs",
	"Black d'hide chaps",
	"Red d'hide chaps",
	"Blue d'hide chaps",
	"Green d'hide chaps",
	"Studded chaps",
	"Snakeskin chaps",
	"Spined chaps",
	"Frog-leather chaps",
	"Penance skirt",
	"Leather chaps",
	"Ancestral robe bottom",
	"Ahrim's robeskirt",
	"3rd age robe",
	"Elder chaos robe",
	"Infinity bottoms",
	"Mystic robe bottom",
	"Saradomin robe legs",
	"Skeletal bottoms",
	"Monk's robe"
],
"shield": [
	"Avernic defender",
	"Dragonfire shield",
	"Dragon defender",
	"Crystal shield",
	"Dragon sq shield",
	"3rd age kiteshield",
	"Rune kiteshield",
	"Dragon kiteshield",
	"Rune defender",
	"Toktz-ket-xil",
	"Unholy book",
	"Book of balance",
	"Falador shield 1",
	"Falador shield 2",
	"Falador shield 3",
	"Falador shield 4",
	"Elysian spirit shield",
	"Arcane spirit shield",
	"Spectral spirit shield",
	"Mind shield",
	"Ancient wyvern shield",
	"Anti-dragon shield",
	"Twisted buckler",
	"Dragonfire ward",
	"Odium ward",
	"Hard leather shield",
	"Snakeskin shield",
	"Green d'hide shield",
	"Blue d'hide shield",
	"Red d'hide shield",
	"Black d'hide shield",
	"Mage's book",
	"Malediction ward",
	"Tome of fire",
	"Book of law",
	"Book of war",
	"Book of darkness"
],
"hands": [
	"Ferocious gloves",
	"Barrows gloves",
	"Void knight gloves",
	"Tormented bracelet",
	"Dragon gloves",
	"Rune gloves",
	"Adamant gloves",
	"Mithril gloves",
	"Black gloves",
	"Steel gloves",
	"Iron gloves",
	"Bronze gloves",
	"Hardleather gloves",
	"Regen bracelet",
	"Combat bracelet",
	"Granite gloves",
	"Chaos gauntlets",
	"Black d'hide vambraces",
	"Red d'hide vambraces",
	"Blue d'hide vambraces",
	"Green d'hide vambraces",
	"Snakeskin vambraces",
	"Spined gloves",
	"Saradomin bracers",
	"Ranger gloves",
	"Leather gloves",
	"3rd age vambraces",
	"Skeletal gloves",
	"Leather vambraces"
],
"feet": [
	"Primordial boots",
	"Dragon boots",
	"Rune boots",
	"Adamant boots",
	"Climbing boots",
	"Bandos boots",
	"Granite boots",
	"Guardian boots",
	"Boots of stone",
	"Boots of brimstone",
	"White boots",
	"Holy sandals",
	"Devout boots",
	"Pegasian boots",
	"Ranger boots",
	"Saradomin d'hide boots",
	"Snakeskin boots",
	"Spined boots",
	"Frog-leather boots",
	"Runner boots",
	"Eternal boots",
	"Infinity boots",
	"Wizard boots",
	"Mystic boots",
	"Skeletal boots",
	"Fighting boots",
	"Fancy boots"
],
"ring": [
	"Berserker ring (i)",
	"Berserker ring",
	"Warrior ring (i)",
	"Warrior ring",
	"Treasonous ring (i)",
	"Treasonous ring",
	"Tyrannical ring (i)",
	"Tyrannical ring",
	"Ring of the gods",
	"Ring of the gods (i)",
	"Ring of suffering",
	"Ring of suffering (i)",
	"Archers ring (i)",
	"Archers ring",
	"Seers ring (i)",
	"Seers ring",
	"Granite ring",
	"Granite ring (i)",
	"Beacon ring",
	"Brimstone ring",
	"Efaritay's aid",
	"Explorer's ring 1",
    "Explorer's ring 2",
    "Explorer's ring 3",
    "Explorer's ring 4"
],
"ammo": [
	"Holy blessing",
	"Rada's blessing 4",
	"Bronze dart",
	"Iron dart",
	"Steel dart",
	"Black dart",
	"Mithril dart",
	"Adamant dart",
	"Rune dart",
	"Dragon dart",
	"Bronze knife",
	"Iron knife",
	"Steel knife",
	"Black knife",
	"Mithril knife",
	"Adamant knife",
	"Rune knife",
	"Dragon knife",
	"Bronze arrow",
	"Iron arrow",
	"Steel arrow",
	"Mithril arrow",
	"Adamant arrow",
	"Rune arrow",
	"Amethyst arrow",
	"Dragon arrow",
	"Bronze javelin",
	"Iron javelin",
	"Steel javelin",
	"Mithril javelin",
	"Adamant javelin",
	"Rune javelin",
	"Amethyst javelin",
	"Dragon javelin",
	"Bolt rack",
	"Broad bolts",
	"Opal bolts (e)",
	"Opal dragon bolts (e)",
	"Jade bolts",
	"Jade dragon bolts",
	"Pearl bolts (e)",
	"Pearl dragon bolts (e)",
	"Topaz bolts",
	"Topaz dragon bolts",
	"Sapphire bolts",
	"Sapphire dragon bolts",
	"Emerald bolts (e)",
	"Emerald dragon bolts (e)",
	"Ruby bolts (e)",
	"Ruby dragon bolts (e)",
	"Diamond bolts (e)",
	"Diamond dragon bolts (e)",
	"Dragonstone bolts (e)",
	"Dragonstone dragon bolts (e)",
	"Onyx bolts (e)",
	"Onyx dragon bolts (e)",
	"Bone bolts",
	"Dragon bolts",
	"Amethyst broad bolts",
	"Runite bolts",
	"Adamant bolts",
	"Mithril bolts",
	"Steel bolts",
	"Iron bolts",
	"Bronze bolts",
	"Silver bolts",
	"Blurite bolts"
]
}