monster_names = ["Aberrant spectre",
"Abyssal demon",
"Abyssal sire (first three phases)",
"Abyssal sire (p4)",
"Respitory system",
"Adamant dragon",
"Ahrim",
"Alchemical Hydra",
"Al-Kharid warrior",
"Ammonite Crab",
"Ancient Wyvern",
"Ancient Zygomite",
"Ankou (75)",
"Ankou (82)",
"Ankou (86)",
"Ankou (98)",
"Ankou (95)",
"Archer",
"Arrg (normal)",
"Arrg (hard)",
"Aviansie (73)",
"Aviansie (79) [1]",
"Aviansie (79) [2]",
"Aviansie (84)",
"Aviansie (92)",
"Aviansie (94)",
"Aviansie (97) [1]",
"Aviansie (97) [2]",
"Aviansie (137)",
"Aviansie (148)",
"Baby black dragon",
"Baby blue dragon",
"Balfrug Kreeyath",
"Bandit (57) (Bandit Camp)",
"Bandit (74) (Bandit Camp)",
"Bandit (130) (wildy)",
"Banshee",
"Barbarian (9)",
"Barbarian (10)",
"Barbarian (15)",
"Barbarian (17)",
"Basilisk",
"Bat",
"Bear cub",
"Bedabin Nomad Fighter",
"Big Wolf",
"Black bear",
"Black demon (172)",
"Black demon (178)",
"Black demon (184)",
"Black demon (188)",
"Black demon (normal)",
"Black demon (hard)",
"Black dragon (227)",
"Black dragon (247)",
"Black Guard",
"Black knight",
"Black knight titan (normal)",
"Black knight titan (hard)",
"Black unicorn",
"Bloodveld (76)",
"Bloodveld (81)",
"Blue dragon",
"Bouncer (normal)",
"Bouncer (hard)",
"Bree",
"Brine rat",
"Bronze dragon (131)",
"Bronze dragon (143)",
"Brutal black dragon",
"Brutal blue dragon",
"Brutal green dragon",
"Brutal red dragon",
"Callisto",
"Catablepon (49)",
"Catablepon (64)",
"Catablepon (68)",
"Cave crawler",
"Cave horror",
"Cave kraken",
"Cerberus",
"Chaos druid",
"Chaos dwarf",
"Chaos elemental",
"Chaos fanatic",
"Chicken",
"Cockatrice",
"Commander Zilyana",
"Corsair Traitor",
"Corsair Traitor (hard)",
"Corporeal beast",
"Count Draynor (normal)",
"Count Draynor (hard)",
"Cow",
"Cow calf",
"Crawling hand (8)",
"Crawling hand (12)",
"Crazy archaeologist",
"Cyclops (zoo)",
"Cyclops (gwd)",
"Cyclops (56)",
"Cyclops (76)",
"Dad (normal)",
"Dad (hard)",
"Dagannoth (74)",
"Dagannoth (92)",
"Dagannoth Prime",
"Dagannoth Rex",
"Dagannoth Supreme",
"Dark beast",
"Dark warrior",
"Dark wizard (7)",
"Dark wizard (20)",
"Dawn",
"Deadly red spider",
"Demonic gorilla",
"Deranged Archaeologist",
"Deviant spectre",
"Dharok",
"Drake",
"Druid",
"Duck",
"Dusk (285)",
"Dusk (366)",
"Dust devil (93)",
"Dust devil (110)",
"Dwarf (10)",
"Dwarf gang member (44)",
"Dwarf gang member (48)",
"Dwarf gang member (49)",
"Earth warrior",
"Elder chaos druid",
"Elf warrior (melee)",
"Elf warrior (ranged)",
"Ent",
"Farmer",
"Fire Giant (86)",
"Fire Giant (104)",
"Fire Giant (109)",
"Flesh Crawler (28)",
"Flesh Crawler (35)",
"Flesh Crawler (41)",
"Flight Kilisa",
"Flockleader Geerin",
"Fortress Guard",
"Gardener (3)",
"Gardener (4)",
"Gargoyle",
"General Graardor",
"Ghost (19)",
"Ghost (76)",
"Ghost (77)",
"Giant bat",
"Giant Mole",
"Giant rat (3)",
"Giant rat (6)",
"Giant spider (2)",
"Giant spider (27)",
"Giant spider (50)",
"Giant scarab",
"Goblin (2)",
"Goblin (5)",
"Goblin (5)",
"Gorak (145) [Plane]",
"Gorak (149) [Gwd]",
"Greater demon (92)",
"Greater demon (100)",
"Greater demon (101)",
"Greater demon (104)",
"Greater demon (113)",
"Greater nechryael",
"Greater skeleton hellhound",
"Green dragon (79)",
"Green dragon (88)",
"Grizzly bear",
"Growler",
"Guard (20)",
"Guard (19)",
"Guard (21)",
"Guard (22)",
"Guard (22)",
"Guard (21)",
"Guard dog",
"Gunthor the brave",
"Guthan",
"Hellhound (122)",
"Hellhound (136)",
"Hero",
"Hill giant",
"Hobgoblin (28)",
"Hobgoblin (42)",
"Hoop Snake",
"Hydra",
"Ice troll (120)",
"Ice troll (121)",
"Ice troll (123)",
"Ice troll (124)",
"Ice Troll King (normal)",
"Ice Troll King (hard)",
"Ice giant (53)",
"Ice giant (67)",
"Ice spider",
"Ice warrior",
"Icefiend",
"Imp",
"Infernal Mage",
"Iron dragon [brimhaven]",
"Iron dragon [catacombs]",
"Jailer",
"Jal-Ak (165)",
"Jal-AkRek-Xil",
"Jal-AkRek-Mej",
"Jal-AkRek-Ket",
"Jal-ImKot (240)",
"Jal-MejJak",
"Jal-MejRah (85)",
"Jal-Nib (32)",
"Jal-Xil",
"Jal-Zek",
"JalTok-Jad (900)",
"Jelly",
"Jogre",
"Jogre [Gwd]",
"Jungle demon (normal)",
"Jungle demon (hard)",
"Kalphite guardian",
"Kalphite queen (1st)",
"Kalphite queen (2nd)",
"Kalphite soldier",
"Kalphite worker",
"Karil",
"Ket-Zek (360)",
"Khazard warlord (normal)",
"Khazard warlord (hard)",
"King black dragon",
"King Roald (normal)",
"King Roald (hard)",
"King Sand Crab",
"King Scorpion",
"Knight of Ardougne",
"Kourend guard",
"Kourend head guard",
"Kraken",
"Kree'arra",
"K'ril Tsutsaroth",
"Kurask",
"Lava dragon",
"Lesser demon (82)",
"Lesser demon (87)",
"Lesser demon (94)",
"Lizardman (53)",
"Lizardman (62)",
"Lizardman brute",
"Lizardman shaman",
"Lobstrosity",
"Locust rider (melee)",
"Locust rider (ranged)",
"Long-tailed Wyvern",
"Magic axe",
"Mammoth",
"Man (2)",
"Man (3)",
"Maniacal monkey",
"Me (normal)",
"Me (hard)",
"Mithril dragon",
"Monk",
"Monk of Zamorak (17)",
"Monk of Zamorak (22)",
"Monkey",
"Monkey Guard",
"Monkey Zombie (82)",
"Monkey Zombie (98)",
"Monkey Zombie (129)",
"Moss giant",
"Moss giant (normal)",
"Moss giant (hard)",
"Mountain troll (69)",
"Mountain troll (71)",
"Mourner (11)",
"Mourner (18)",
"Mourner (24)",
"Mourner (108)",
"Mugger",
"Mutated bloodveld",
"Nazastarool zombie (normal)",
"Nazastarool skeleton (normal)",
"Nazastarool ghost (normal)",
"Nazastarool zombie (hard)",
"Nazastarool skeleton (hard)",
"Nazastarool ghost (hard)",
"Nechryael",
"Night beast",
"Obor",
"Ogre",
"Ork",
"Paladin",
"Penguin",
"Pirate",
"Poison scorpion",
"Poison spider",
"Possessed pickaxe",
"Pyrefiend",
"Rat",
"Revenant imp",
"Revenant goblin",
"Revenant pyrefiend",
"Revenant hobgoblin",
"Revenant cyclops",
"Revenant hellhound",
"Revenant demon",
"Revenant ork",
"Revenant dark beast",
"Revenant knight",
"Revenant dragon",
"Red dragon",
"Robert the Strong",
"Rock crab",
"Rune dragon",
"Rockslug",
"Rogue",
"Sand crab",
"Sand Snake",
"Sand Snake (hard)",
"Scarab mage",
"Scarab swarm",
"Scarabs",
"Scorpia",
"Scorpion (14)",
"Scorpion (37)",
"Scorpion (59)",
"Seagull (2)",
"Seagull (3)",
"Sergeant Grimspike",
"Sergeant Steelwill",
"Sergeant Strongstack",
"Shade (140)",
"Shade (159)",
"Skeletal wyvern",
"Skeleton (21)",
"Skeleton (22)",
"Skeleton (25)",
"Skeleton (45)",
"Skeleton (60)",
"Skeleton (68)",
"Skeleton (Ape Toll)",
"Skeleton hellhound (normal)",
"Skeleton hellhound (hard)",
"Skotizo",
"Slagilith (normal)",
"Slagilith (hard)",
"Smoke devil",
"Snake",
"Soldier (tier 1)",
"Soldier (tier 2)",
"Soldier (tier 3)",
"Soldier (tier 4)",
"Soldier (tier 5)",
"Spider (1)",
"Spider (24)",
"Spinolyp",
"Spiritual mage (Arma)",
"Spiritual mage (Bandos)",
"Spiritual mage (Sara)",
"Spiritual mage (Zamorak)",
"Spiritual ranger (Arma)",
"Spiritual ranger (Bandos)",
"Spiritual ranger (Sara)",
"Spiritual ranger (Zamorak)",
"Spiritual warrior (Arma)",
"Spiritual warrior (Bandos)",
"Spiritual warrior (Sara)",
"Spiritual warrior (Zamorak)",
"Spitting Wyvern",
"Starlight",
"Steel dragon [brimhaven]",
"Steel dragon [catacombs]",
"Suit of armour",
"Suqah",
"Taloned Wyvern",
"Tar Monster",
"The Everlasting (normal)",
"The Everlasting (hard)",
"The Inadequacy (normal)",
"The Inadequacy (hard)",
"The Kendal (normal)",
"The Kendal (hard)",
"The Untouchable (normal)",
"The Untouchable (hard)",
"Thermonuclear smoke devil",
"Thief",
"Thug",
"Tok-Xil (90)",
"Torag",
"Tree spirit (normal)",
"Tree spirit (hard)",
"Treus dayth (normal)",
"Treus dayth (hard)",
"Troll general",
"Tstanon Karlak",
"Turoth (83)",
"Turoth (85)",
"Turoth (87)",
"Twisted banshee",
"TzKal-Zuk (1400)",
"Tz-Kek (22)",
"Tz-Kek (45)",
"Tz-Kih (22)",
"TzTok-Jad",
"TzHaar-Hur (74)",
"TzHaar-Ket (149)",
"TzHaar-Xil (133)",
"Unicorn",
"Venenatis",
"Verac",
"Vet'ion",
"Vorkath",
"Vorkath (quest)",
"Warped jelly",
"Warrior woman",
"Waterfiend",
"White Knight",
"White Knight (proselyte)",
"White Knight (acolyte)",
"White Knight (partisan)",
"White wolf (25)",
"White wolf (38)",
"Wingman Skree",
"Witch's experiment 1st (hard)",
"Witch's experiment 2nd (hard)",
"Witch's experiment 3rd (hard)",
"Witch's experiment 4th (hard)",
"Wolf",
"Woman (3)",
"Woman (4)",
"Woman (14)",
"Wyrm",
"Yak",
"Yt-HurKot (141)",
"Yt-MejKot (180)",
"Zakl'n Gritch",
"Zombie (13)",
"Zombie (18)",
"Zombie (24)",
"Zulrah (crimson)",
"Zulrah (green)",
"Zulrah (turquoise)",
"Zygomite (74)",
"Zygomite (86)",
"Maiden of Sugadinti",
"Pestilent Bloat",
"Sotetseg",
"Verzik (Throne)",
"Verzik (Vampire)",
"Verzik (Spider)",
"Nylocas Matomenos",
"Xarpus",
"Nylocas Vasilias",
"Nylocas Toxobolos (small)",
"Nylocas Toxobolos (big)",
"Nylocas Ischyros (small)",
"Nylocas Ischyros (big)",
"Nylocas Hagios (small)",
"Nylocas Hagios (big)",
"Vasa nistirio",
"Glowing crystal",
"Tekton",
"Tekton (enraged)",
"Vespula",
"Abyssal portal",
"Vanguard (melee)",
"Vanguard (ranged)",
"Vanguard (magic)",
"Muttadiles (small)",
"Muttadiles (big)",
"Guardian",
"Skeletal mystics",
"Shamans",
"Scavenger beast",
"Ice demon",
"Deathly mage",
"Deathly ranger",
"Great Olm (head)",
"Great Olm (melee hand)",
"Great Olm (mage hand)",
"Vasa nistirio CM",
"Glowing crystal CM",
"Tekton CM",
"Tekton CM (enraged)",
"Vespula CM",
"Abyssal portal CM",
"Vanguard CM (melee)",
"Vanguard CM (ranged)",
"Vanguard CM (magic)",
"Muttadiles CM (small)",
"Muttadiles CM (big)",
"Guardian CM",
"Skeletal mystics CM",
"Lizardman Shamans CM",
"Scavenger beast CM",
"Ice demon CM",
"Deathly mage CM",
"Deathly ranger CM",
"Great Olm (head CM)",
"Great Olm (melee hand CM)",
"Great Olm (mage hand CM)",
"Mimic",
"Sarachnis",
"Basilisk knight",
"Hespori",
"Undead druid",
"The Nightmare",
"Parasite (lvl 57)",
"Parasite (lvl 86)",
"Husk",
"Sleepwalker",
"Totem",
"Crystalline Hunllef",
"Corrupted Hunllef",
"Crystalline Spider",
"Corrupted Spider",
"Crystalline Rat",
"Corrupted Rat",
"Crystalline Bat",
"Corrupted Bat",
"Crystalline Unicorn",
"Corrupted Unicorn",
"Crystalline Scorpion",
"Corrupted Scorpion",
"Crystalline Wolf",
"Corrupted Wolf",
"Crystalline Bear",
"Corrupted Bear",
"Crystalline Dragon",
"Corrupted Dragon",
"Crystalline Dark Beast",
"Corrupted Dark Beast",
"Vyrewatch Sentinel",
"Vampyre Juvinate (119)",
"Vampyre Juvinate (50)",
"Vampyre Juvinate (54)",
"Vampyre Juvinate (54, Meiyerditch/Darkmeyer)",
"Vampyre Juvinate (59)",
"Vampyre Juvinate (75)",
"Vampyre Juvinate (90)",
"Damien Leucurte",
"Ranis Draken",
"Vanstrom Klause",
"Vyrewatch (105)",
"Vyrewatch (110)",
"Vyrewatch (120)",
"Vyrewatch (125)",
"Vyrewatch (87)",
"Dessous (normal)",
"Dessous (hard)",
"Feral Vampyre (100)",
"Feral Vampyre (130)",
"Feral Vampyre (61)",
"Feral Vampyre (64)",
"Feral Vampyre (70)",
"Feral Vampyre (72)",
"Feral Vampyre (77)",
"Kroy",
"Vampyre Juvenile"]